DT.WEB/Controllers/UserManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using DT.DAL;
using DT.DTO;
using DT.WEB.Models;

namespace DT.WEB.Controllers
{
    public class UserManagementController : BaseController
    {
        // GET: UserManagement
        public ActionResult Index(int role_id = 0)
        {
            ViewBag.Title = LOCAL.Objects.Tables.Users;
            ViewBag.SubDirectory = LOCAL.Objects.Tables.Users;
            ViewBag.role_id = role_id;
            List<User> users = new List<User>();
            if (CurrentUser.role_id == 1 || CurrentUser.role_id == 2)
            {
                using (Repository<User> Repository = new Repository<User>())
                {
                    users = Repository.SelectByAll().ToList();
                }
                if (role_id != 0)
                    users = users.Where(x => x.role_id == role_id).ToList();
                return View(users);
            }
            else if (CurrentUser.role_id == 3)
            {
                using (Repository<User> Repository = new Repository<User>())
                {
                    users = Repository.MultiSelectByQuery(t => t.is_active &&
                    t.created_by == CurrentUser.id).ToList();
                }
                if (role_id != 0)
                    users = users.Where(x => x.role_id == role_id).ToList();
                return View(users);
            }
            else
                return RedirectToAction("Index", "Home");
        }
        public ActionResult AddUpdate(int id = 0,int role_id=0)
        {
            User user = new User();
            user.role_id = role_id;
            if (id != 0)
                using (Repository<User> Repository = new Repository<User>())
                {
                    user = Repository.SingleSelectByQuery(x => x.id == id && x.is_active); 
                }
            return PartialView("_AddUpdatePartial",user);
        }

        public ActionResult GetTeachers(string search = "")
        {
            string s = "";
            if (!string.IsNullOrEmpty(search))
                s = search.ToLower().Trim();
            var list = from u in StaticDB.Users
                       where u.role_id == 3
                       where u.name.ToLower().Contains(s) ||
                        u.lastname.ToLower().Contains(s) ||
                        u.mail.ToLower().Contains(s)
                       select new
                       {
                           id = u.id,
                           text = $"{u.name} {u.lastname} ({u.mail})"
                       };
            return Json(new { results = list, pagination = new { more = false } }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult AddUpdate(User user)
        {
            using (Repository<User> Repository = new Repository<User>())
            {
                var us = Repository.SingleSelectByQuery (x => x.id != user.id && x.mail.Trim().ToLower().Equals(user.mail.Trim().ToLower()));

                if (us == null)
                {
                    user.confirmation_expiration = DateTime.Now;
                    user.is_allowed = true;
                    user.is_confirmed = true;
                    user.is_subscribed = true;
                    user.is_profile_visible = true;
                    user.is_active = true;
                    user.ui_language = "en";
                    if (user.id == 0)
                        user = Repository.Inserted(user);
                    else
                        user = Repository.Updated(user);
                }
                else
                {
                    return Json(new { Result = false, Message="This mail exists!"});
                }

            }
            return Json(new { Result = true, User = user });
        }

        public ActionResult Details(int id)
        {

            User user = new User();
            using (Repository<User> Repository = new Repository<User>())
            {
                Repository.Include("ClassStudents");
                Repository.Include("SessionTaskParticipants");
                user = Repository.SingleSelectByQuery(x => x.id == id && x.is_active);
            }
            if (user == null)
                return RedirectToAction("Index");
            ViewBag.Title = "Profile";
            ViewBag.SubDirectory = "User Details";
            List<TimelineModel> timelineItems = new List<TimelineModel>();
            using (Ctx ctx = new Ctx())
            {
                var taskTimelines = from x in ctx.Tasks.Where(x => x.created_by == id && x.is_active)
                                    select new TimelineModel
                                    {
                                        Table = "Task",
                                        Icon = "fas fa-tasks",
                                        Color = "bg-blue",
                                        Object = x,
                                        CreatedDate = x.created_date,
                                        Details = x.target_subject
                                    };
                timelineItems.AddRange(taskTimelines.ToList());


                var userTimelines = from x in ctx.Users.Where(x => x.created_by == id && x.is_active)
                                    select new TimelineModel
                                    {
                                        Table = "User",
                                        Icon = "fas fa-students",
                                        Color = "bg-cyan",
                                        Object = x,
                                        CreatedDate = x.created_date,
                                        Details = x.details
                                    };
                timelineItems.AddRange(userTimelines.ToList());


                var materialTimeLines = from x in ctx.Materials.Where(x => x.created_by == id && x.is_active)
                                    select new TimelineModel
                                    {
                                        Table = "Material",
                                        Icon = "fas fa-photo-video",
                                        Color = "bg-bubbles",
                                        Object = x,
                                        CreatedDate = x.created_date,
                                        Details = x.details
                                    };
                timelineItems.AddRange(materialTimeLines.ToList());


                var sequenceTimeLines = from x in ctx.Sequences.Where(x => x.created_by == id && x.is_active)
                                       select new TimelineModel
                                       {
                                           Table = "Sequence",
                                           Icon = "fas fa-calendar-alt",
                                           Color = "bg-blue",
                                           Object = x,
                                           CreatedDate = x.created_date,
                                           Details = x.details
                                       };
                timelineItems.AddRange(sequenceTimeLines.ToList());
            }

            ViewData["TimelineItems"] = timelineItems.OrderByDescending(x => x.CreatedDate).ToList();
            return View(user);
        }
        public ActionResult Delete(int id)
        {
            using (Repository<User> Repository = new Repository<User>())
            {
                User user = Repository.SingleSelectByQuery(x => x.id == id && x.is_active);
                Repository.SoftDeleting(user);
            }
            return RedirectToAction("Index");
        }

        public ActionResult ShowPassword(int user_id)
        {
            User user = StaticDB.Users.GetById(user_id);
            return PartialView("PartialShowPassword", user);
        }
        public ActionResult SetProp(int user_id, string property, bool value)
        {
            User user = StaticDB.Users.GetById(user_id);
            if (user == null)
                return Json(new { Result = false }, JsonRequestBehavior.AllowGet);
            else
            {

                using (Repository<User> Repository = new Repository<User>())
                {
                    user = Repository.SingleSelectByQuery(x => x.id == user_id);
                    PropertyInfo propertyInfo = typeof(User).GetProperty(property);
                    propertyInfo.SetValue(user, value);
                    Repository.Updating(user);
                }
                return Json(new { Result = true }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

DT.WEB/Views/UserManagement/PartialShowPassword.cshtml
@model User
<div class="modal-dialog" id="user-pass-dialog">
    <div class="modal-content">

        <!-- Modal Header -->
        <div class="modal-header">
            <h4 class="modal-title">@DT.LOCAL.Objects.Columns.password</h4>
            <button type="button" class="close" onclick="CloseModal(this)" data-target="#user-pass-dialog"><i class="fas fa-times"></i></button>
        </div>
        <!-- Modal body -->
        <div class="modal-body">
            <div class="form-group">
                <h2>
                    @Model.password
                </h2>
            </div>
        </div>

        <!-- Modal footer -->
        <div class="modal-footer">
            <button type="button" class="btn btn-primary" data-dismiss="modal">OK</button>
        </div>
    </div>
</div>

DT.WEB/Views/UserManagement/_AddUpdatePartial.cshtml
@{ 
    User currentUser = Request.User();
    
}
@model User

@using (Html.BeginForm())
{
    @Html.HiddenFor(x => x.id)
    @Html.HiddenFor(x => x.created_by)
    @Html.HiddenFor(x => x.created_date)
    @Html.HiddenFor(x => x.is_active)
    <div class="modal-dialog modal-lg" id="user-edit-dialog">
        <div class="modal-content">
            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">@(Model.id == 0? DT.LOCAL.Components.Labels.CreateNew: DT.LOCAL.Components.Labels.Editing)</h4>
                <button type="button" class="close" data-dismiss="modal"><i class="fas fa-times"></i></button>
            </div>
            <!-- Modal body -->
            <div class="modal-body">
                @Html.Partial(currentUser.role_id == 1 ||currentUser.role_id == 2 ? "_UserEditForm_Admin": "_UserEditForm", Model)
            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">@DT.LOCAL.Components.Buttons.Cancel</button>
                <button type="button" id="btn-save-company" class="btn btn-success" onclick="SaveUser();">@DT.LOCAL.Components.Buttons.Save</button>
            </div>
        </div>
    </div>
}

<script>

    var entity = @Html.Raw(Model.ToJson());
    jQuery(function () {
        SetProps(entity.role_id);
        console.log(JSON.stringify(entity));
        $('#user-mail').val(entity.mail);
        $('#user-name').val(entity.name);
        $('#user-lastname').val(entity.lastname);
        $('#user-password').val(entity.password);
        if (@currentUser.role_id == 1) {
            $('#user-confirm_password').val(entity.password);
        }
        $('#user-confirm_password').val();
        $('#user-bd').val(entity.birth);
        $('#user-pl').val(entity.proficiency_level);
        $('#user-pl').trigger('change');
        $('#user-role').change(function () {
            if ($(this).val() == 3)
                $('.teacher-prop').removeClass('hidden');
            else
                $('.teacher-prop').addClass('hidden');
        });
        $('#user-role').val(entity.role_id);
        $('#user-role').trigger('change');
        $('#user-role_id').change(function () {
            SetProps($(this).val());
        });
    });
    function SetProps(role_id) {
        if (role_id == 3) {
            $('.student-prop').addClass('hidden');
            $('.teacher-prop').removeClass('hidden');
        }
        else if (role_id == 4) {
            $('.teacher-prop').addClass('hidden');
            $('.student-prop').removeClass('hidden');
        } else {
            $('.student-prop').addClass('hidden');
            $('.teacher-prop').addClass('hidden');
        }
    }
    function SaveUser() {

        entity.name = $('#user-name').val();
        entity.lastname = $('#user-lastname').val();
        entity.role_id = $('#user-role_id').val();
        entity.mail = $('#user-mail').val();
        entity.password = $('#user-password').val();
        entity.confirm_password = $('#user-confirm_password').val();
        entity.birth = new Date($('#user-bd').val());
        entity.proficiency_level = $('#user-pl').val();

        console.log('ENTITY : ' + JSON.stringify(entity));
        if (!entity.mail) {
            ShowAlert('@DT.LOCAL.Messages.Warnings.DialogTitle', '@string.Format(DT.LOCAL.Messages.Warnings.FieldRequired, DT.LOCAL.Objects.Columns.mail)', '@DT.LOCAL.Components.Buttons.Ok');
        }
        else if (!entity.password) {
            ShowAlert('@DT.LOCAL.Messages.Warnings.DialogTitle', '@string.Format(DT.LOCAL.Messages.Warnings.FieldRequired, DT.LOCAL.Objects.Columns.password)', '@DT.LOCAL.Components.Buttons.Ok');
        }
        else if (!entity.confirm_password && @currentUser.role_id != 1) {
            ShowAlert('@DT.LOCAL.Messages.Warnings.DialogTitle', '@string.Format(DT.LOCAL.Messages.Warnings.FieldRequired, DT.LOCAL.Objects.Columns.confirm_password)', '@DT.LOCAL.Components.Buttons.Ok');
        }
        else if (entity.password != entity.confirm_password) {
            ShowAlert('@DT.LOCAL.Messages.Warnings.DialogTitle', 'Password and confirmation are not same!', '@DT.LOCAL.Components.Buttons.Ok');
        }
        else if (!entity.birth) {
            ShowAlert('@DT.LOCAL.Messages.Warnings.DialogTitle', '@string.Format(DT.LOCAL.Messages.Warnings.FieldRequired, DT.LOCAL.Objects.Columns.birth_date)', '@DT.LOCAL.Components.Buttons.Ok');
        }
        else if (!entity.role_id) {
            ShowAlert('@DT.LOCAL.Messages.Warnings.DialogTitle', '@string.Format(DT.LOCAL.Messages.Warnings.FieldRequired, DT.LOCAL.Objects.Columns.role_id)', '@DT.LOCAL.Components.Buttons.Ok');
        }
        else {
            if (entity.role_id == 1 || entity.role_id == 2)
            {
                var pass = prompt('You need to enter your password to continue:');
                if (!pass || pass != Credentials.User.password)
                    return;
                else
                    PostData();
            }
            else
                PostData();

        }
    }
    function PostData() {
        $.ajax({
                url: '@Url.Action("AddUpdate", "UserManagement")',
                type: "POST",
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                data: JSON.stringify(entity),
                success: function (data) {
                    if (data.Result) {
                        $(PartialModal).modal('toggle');
                        location.reload();
                    }else
                        ShowAlert('@DT.LOCAL.Messages.Warnings.DialogTitle', data.Message, '@DT.LOCAL.Components.Buttons.Ok');
                },
                error: function (XMLHttpRequest, textStatus, errorThrown) {
                    ShowAlert('@DT.LOCAL.Messages.Warnings.DialogTitle', errorThrown, '@DT.LOCAL.Components.Buttons.Ok');
                }
            });
    }
</script>

DT.WEB/Views/UserManagement/_UserEditForm.cshtml
@model User

@{
    User current_user = Request.User();
    string birth = "";
    if (Model.birth != null)
    {
        birth = Convert.ToDateTime(Model.birth).ToString("yyyy-MM-dd");
    }
}
<style>
    .teacher-prop {
        transition: all ease-in-out 0.2s;
    }
</style>

@Html.HiddenFor(x => x.role_id, new { id = "user-role_id" })
@Html.HiddenFor(x => x.mail, new { id = "user-mail" })
<div class="row">
    <div class="col-6">
        <div class="form-group">
            <label for="user-name">@DT.LOCAL.Components.Labels.Name</label>
            @Html.TextBoxFor(x => x.name, new { @class = "form-control", type = "text", id = "user-name", autocomplete = "off" })
        </div>
    </div>
    <div class="col-6">
        <div class="form-group">
            <label for="user-lastname">@DT.LOCAL.Components.Labels.Last_Name</label>
            @Html.TextBoxFor(x => x.lastname, new { @class = "form-control", type = "text", id = "user-lastname", autocomplete = "off" })
        </div>
    </div>

    <div class="col-4">
        <div class="form-group">
            <label for="user-password">@DT.LOCAL.Objects.Columns.password</label>
            @Html.TextBoxFor(x => x.password, new { @class = "form-control", type = "password", id = "user-password", autocomplete = "off" })
        </div>
    </div>
    <div class="col-4">
        <div class="form-group">
            <label for="user-confirm_password">@DT.LOCAL.Objects.Columns.confirm_password</label>
            @Html.TextBoxFor(x => x.confirm_password, new { @class = "form-control", type = "password", id = "user-confirm_password", autocomplete = "off" })
        </div>
    </div>
    <div class="col-4">
        <div class="form-group">
            <label for="user-ui_language">@DT.LOCAL.Objects.Columns.ui_language</label>
            <select name="ui_language" id="user-ui_language" class="form-control" required>
                <option>@string.Format(DT.LOCAL.Components.Labels.PleaseChooseX, DT.LOCAL.Objects.Columns.language_id)</option>
                @foreach (Language language in StaticDB.Languages.Where(x => x.has_ui))
                {
                    <option value="@language.iso_code" @(current_user.ui_language.Trim().Equals(language.iso_code.Trim()) ? "selected" : "")>@language.name</option>
                }
            </select>
        </div>
    </div>

    <div class="col-12 teacher-prop">
        <div class="form-group">
            <label for="user-institution">@DT.LOCAL.Objects.Columns.institution</label>
            @Html.TextBoxFor(x => x.institution, new { @class = "form-control", id = "user-institution", autocomplete = "off" })
        </div>
    </div>

    <div class="col-6 teacher-prop">
        <div class="form-group">
            <label for="user-department">@DT.LOCAL.Objects.Columns.department</label>
            @Html.TextBoxFor(x => x.department, new { @class = "form-control", id = "user-department", autocomplete = "off" })
        </div>
    </div>
    <div class="col-6 teacher-prop">
        <div class="form-group">
            <label for="user-title">@DT.LOCAL.Objects.Columns.title</label>
            @Html.TextBoxFor(x => x.title, new { @class = "form-control", id = "user-title", autocomplete = "off" })
        </div>
    </div>

    <div class="col-6 student-prop">
        <div class="form-group">
            <label for="bd-group">@DT.LOCAL.Objects.Columns.birth_date</label>
            <div class="input-group date" data-type="date" id="bd-group" data-target-input="nearest">
                <input type="text" class="form-control datetimepicker-input" data-target="#bd-group" required id="user-bd" value="@birth" />
                <div class="input-group-append" data-target="#bd-group" data-toggle="datetimepicker">
                    <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-6 student-prop">
        <div class="form-group">
            <label for="user-pl">@DT.LOCAL.Objects.Columns.target_proficiency_level</label>
            <select id="user-pl" class="form-control custom-select" name="proficiency_level">
                <option selected disabled>Select one</option>
                @foreach (var item in WebUtils.GetResourcesByType(typeof(DT.LOCAL.Enums.Proficiencies), true))
                {
                    <option value="@item.Key">@item.Value</option>
                }
            </select>
        </div>
    </div>
</div>

DT.WEB/Views/UserManagement/_UserEditForm_Admin.cshtml
@model User

@{
    User current_user = Request.User();
    string birth = "";
    if (Model.birth != null)
    {
        birth = Convert.ToDateTime(Model.birth).ToString("yyyy-MM-dd");
    }
}
<style>
    .teacher-prop {
        transition: all ease-in-out 0.2s;
    }
</style>
@if (Model.id == 0)
{
    @Html.HiddenFor(x => x.is_allowed, true)
    @Html.HiddenFor(x => x.is_confirmed, true)
}
<div class="row">
    <div class="col-6">
        <div class="form-group">
            <label for="user-name">@DT.LOCAL.Components.Labels.Name</label>
            @Html.TextBoxFor(x => x.name, new { @class = "form-control", type = "text", id = "user-name", autocomplete = "off" })
        </div>
    </div>
    <div class="col-6">
        <div class="form-group">
            <label for="user-lastname">@DT.LOCAL.Components.Labels.Last_Name</label>
            @Html.TextBoxFor(x => x.lastname, new { @class = "form-control", type = "text", id = "user-lastname", autocomplete = "off" })
        </div>
    </div>

    <div class="col-6">
        <div class="form-group">
            <label for="user-role_id">@DT.LOCAL.Components.Labels.Role</label>
            <select id="user-role_id" class="form-control select2" name="role_id">
                <option selected disabled>Select one</option>
                @foreach (var role in StaticDB.Roles)
                {
                    <option @(Model.role_id == role.id ? "selected" : "") value="@role.id">@role.title</option>
                }
            </select>
        </div>
    </div>

    <div class="col-6" id="mail-part">
        <div class="form-group">
            <label for="user-mail">@DT.LOCAL.Components.Labels.Mail</label>
            @Html.TextBoxFor(x => x.mail, new { @class = "form-control", type = "email", id = "user-mail", autocomplete = "off" })
        </div>
    </div>

    <div class="col-4">
        <div class="form-group">
            <label for="user-password">@DT.LOCAL.Objects.Columns.password</label>
            @Html.TextBoxFor(x => x.password, new { @class = "form-control", type = "password", id = "user-password", autocomplete = "off" })
        </div>
    </div>
    <div class="col-4">
        <div class="form-group">
            <label for="user-confirm_password">@DT.LOCAL.Objects.Columns.confirm_password</label>
            @Html.TextBoxFor(x => x.confirm_password, new { @class = "form-control", type = "password", id = "user-confirm_password", autocomplete = "off" })
        </div>
    </div>
    <div class="col-4">
        <div class="form-group">
            <label for="user-ui_language">@DT.LOCAL.Objects.Columns.ui_language</label>
            <select name="ui_language" id="user-ui_language" class="form-control" required>
                <option>@string.Format(DT.LOCAL.Components.Labels.PleaseChooseX, DT.LOCAL.Objects.Columns.language_id)</option>
                @foreach (Language language in StaticDB.Languages.Where(x => x.has_ui))
                {
                    <option value="@language.iso_code" @(current_user.ui_language.Trim().Equals(language.iso_code.Trim()) ? "selected" : "")>@language.name</option>
                }
            </select>
        </div>
    </div>

    <div class="col-12 teacher-prop">
        <div class="form-group">
            <label for="user-institution">@DT.LOCAL.Objects.Columns.institution</label>
            @Html.TextBoxFor(x => x.institution, new { @class = "form-control", id = "user-institution", autocomplete = "off" })
        </div>
    </div>

    <div class="col-6 teacher-prop">
        <div class="form-group">
            <label for="user-department">@DT.LOCAL.Objects.Columns.department</label>
            @Html.TextBoxFor(x => x.department, new { @class = "form-control", id = "user-department", autocomplete = "off" })
        </div>
    </div>
    <div class="col-6 teacher-prop">
        <div class="form-group">
            <label for="user-title">@DT.LOCAL.Objects.Columns.title</label>
            @Html.TextBoxFor(x => x.title, new { @class = "form-control", id = "user-title", autocomplete = "off" })
        </div>
    </div>

    <div class="col-6 student-prop">
        <div class="form-group">
            <label for="bd-group">@DT.LOCAL.Objects.Columns.birth_date</label>
            <div class="input-group date" data-type="date" id="bd-group" data-target-input="nearest">
                <input type="text" class="form-control datetimepicker-input" data-target="#bd-group" required id="user-bd" value="@birth" />
                <div class="input-group-append" data-target="#bd-group" data-toggle="datetimepicker">
                    <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-6 student-prop">
        <div class="form-group">
            <label for="user-pl">@DT.LOCAL.Objects.Columns.target_proficiency_level</label>
            <select id="user-pl" class="form-control custom-select" name="proficiency_level">
                <option selected disabled>Select one</option>
                @foreach (var item in WebUtils.GetResourcesByType(typeof(DT.LOCAL.Enums.Proficiencies), true))
                {
                    <option value="@item.Key">@item.Value</option>
                }
            </select>
        </div>
    </div>
</div>