DT.WEB/Controllers/LanguageManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DT.DAL;
using DT.DTO;
using DT.WEB.Models;

namespace DT.WEB.Controllers
{
    public class LanguageManagementController : BaseController
    {
        // GET: LanguageManagement
        public ActionResult Index()
        {
            ViewBag.Title = LOCAL.Objects.Tables.Languages;
            ViewBag.SubDirectory = LOCAL.Objects.Tables.Languages;
            List<Language> entities = new List<Language>();
            if (CurrentUser.role_id == 1 || CurrentUser.role_id == 2)
            {
                using (Repository<Language> Repository = new Repository<Language>())
                {
                    entities = Repository.SelectByAll().ToList();
                }
                return View(entities);
            }
            else 
                return RedirectToAction("Index", "Home");
        }
        public ActionResult AddUpdate(int id = 0)
        {
            Language entity = new Language();
            if (id != 0)
                using (Repository<Language> Repository = new Repository<Language>())
                {
                    entity = Repository.SingleSelectByQuery(x => x.id == id);
                }
            if(entity == null)
                entity = new Language();
            return PartialView("_AddUpdatePartial",entity);
        }

        [HttpPost]
        public ActionResult AddUpdate(Language entity)
        {
            using (Repository<Language> Repository = new Repository<Language>())
            {

                if (entity.id == 0)
                    entity = Repository.Inserted(entity);
                else
                    entity = Repository.Updated(entity);

            }
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            Language language = StaticDB.Languages.GetById(id);
            if(language == null ||
                StaticDB.TargetLanguages.Count(t=>t.language_id == id) > 0 ||
                StaticDB.ProficiencyLanguages.Count(t=>t.language_id == id) > 0 ||
                StaticDB.Users.Count(x=>x.ui_language.Equals(language.iso_code)) > 0)
                return RedirectToAction("Index");
            using (Repository<Language> Repository = new Repository<Language>())
            {
                Language entity = Repository.SingleSelectByQuery(x => x.id == id);
                Repository.Deleting(entity);
            }
            return RedirectToAction("Index");
        }
    }
}

DT.WEB/Views/LanguageManagement/Index.cshtml
@model List<Language>
 
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    User current_user = Request.User();
}

@section styles{
    <link href="~/Content/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
    <link href="~/Content/plugins/datatables-responsive/css/responsive.bootstrap4.min.css" rel="stylesheet" />
    <link href="~/Content/plugins/datatables-buttons/css/buttons.bootstrap4.min.css" rel="stylesheet" />
    <style>
    </style>
}

<!-- /.card -->
<div class="row">
    <div class="col-12">
        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">
                    <a href="@Request.Url.ToString()">
                        @ViewBag.SubDirectory
                    </a>
                </h3>
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" id="btn-table-create"
                            data-url="@Url.Action("AddUpdate","LanguageManagement")"
                            data-modal="#partial-modal"
                            onclick="PartialShow(this);">
                        <i class="fas fa-plus"></i>&nbsp;@DT.LOCAL.Components.Buttons.CreateNew
                    </button>
                </div>
            </div>
            <div class="card-body">
                <table class="index-table cell-border display table-bordered table-responsive responsive" style="width:100% !important;">
                    <thead>

                        <tr>

                            <th></th>
                            <th>@DT.LOCAL.Objects.Columns.name</th>
                            <th>@DT.LOCAL.Objects.Columns.iso_code</th>
                            <th>@DT.LOCAL.Objects.Columns.locales</th>
                            <th>@DT.LOCAL.Objects.Columns.rtl</th>
                            <th>@DT.LOCAL.Objects.Columns.has_ui</th>
                            <th>@DT.LOCAL.Objects.Columns.flag</th>
                        </tr>

                    </thead>
                    <tbody>

                        @foreach (Language item in Model)
                        {

                        <tr>
                            <td>
                                <div class="btn-group btn-group-sm">
                                    <a href="#"
                                       data-url="@Url.Action("AddUpdate","LanguageManagement",new {id=item.id})"
                                       data-modal="#partial-modal"
                                       onclick="PartialShow(this);"
                                       class="btn btn-default hover-orange"
                                       title="@DT.LOCAL.Components.Buttons.Edit">
                                        <i class="fa fa-pencil-alt"></i>
                                    </a>
                                    <a href="#"
                                       class="btn btn-default hover-orange"
                                       onclick="ConfirmGoLink('@DT.LOCAL.Messages.Questions.ApproveTitle', '@DT.LOCAL.Messages.Warnings.DeleteWarning', '@DT.LOCAL.Components.Buttons.Cancel', '@DT.LOCAL.Components.Buttons.Ok', '@Url.Action("Delete",new {id=item.id })');"
                                       title="@DT.LOCAL.Components.Buttons.Delete">
                                        <i class="fa fa-trash"></i>
                                    </a>
                                </div>
                            </td>
                            <td>@item.name.ToStr()</td>
                            <td>@item.iso_code.ToStr()</td>
                            <td>@item.locales.ToStr()</td>
                            <td>@((bool)item.rtl?DT.LOCAL.Components.Labels.Yes:DT.LOCAL.Components.Labels.No)</td>
                            <td>@((bool)item.has_ui?DT.LOCAL.Components.Labels.Yes:DT.LOCAL.Components.Labels.No)</td>
                            <td>@Request.GetFlag(item, false)</td>
                        </tr>
                        }

                    </tbody>
                </table>
            </div>
            <!-- /.card-footer-->
        </div>
        <!-- /.card -->
    </div>
</div>

@section scripts{
    @Html.Partial("_DatatableScripts")
    <script>
        function CreateNew() {
            ShowPartial('@Url.Action("AddUpdate", "LanguageManagement")', $('.btn-create-new'))
        }
    </script>
}

DT.WEB/Views/LanguageManagement/_AddUpdatePartial.cshtml
@model Language

@using (Html.BeginForm("AddUpdate", "LanguageManagement"))
{
    @Html.HiddenFor(x => x.id)
    <div class="modal-dialog" id="language-edit-dialog">
        <div class="modal-content">
            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">@(Model.id == 0? DT.LOCAL.Components.Labels.CreateNew: DT.LOCAL.Components.Labels.Editing)</h4>
                <button type="button" class="close" onclick="CloseModal(this)" data-target="#language-edit-dialog"><i class="fas fa-times"></i></button>
            </div>
            <!-- Modal body -->
            <div class="modal-body">
                <div class="row">
                    <div class="col-12">
                        <div class="form-group">
                            <label for="entity-name">@DT.LOCAL.Objects.Columns.name</label>
                            @Html.TextBoxFor(x => x.name, new { @class = "form-control", type = "text", id = "entity-name" })
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="form-group">
                            <label for="entity-iso_code">@DT.LOCAL.Objects.Columns.iso_code</label>
                            @Html.TextBoxFor(x => x.iso_code, new { @class = "form-control", type = "text", id = "entity-iso_code" })
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="form-group">
                            <label for="entity-locales">@DT.LOCAL.Objects.Columns.locales</label>
                            @Html.TextBoxFor(x => x.locales, new { @class = "form-control", type = "text", id = "entity-locales" })
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label for="entity-rtl">@DT.LOCAL.Objects.Columns.rtl</label>
                            @Html.CheckBoxFor(x => x.rtl, new { @class = "form-control", id = "entity-rtl" })
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label for="entity-has_ui">@DT.LOCAL.Objects.Columns.has_ui</label>
                            @Html.CheckBoxFor(x => x.has_ui, new { @class = "form-control", id = "entity-has_ui" })
                        </div>
                    </div>
                </div>
            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">@DT.LOCAL.Components.Buttons.Cancel</button>
                <button type="submit" id="btn-save-company" class="btn btn-success">@DT.LOCAL.Components.Buttons.Save</button>
            </div>
        </div>
    </div>
}