DT.WEB/Controllers/ClassManagementController.cs
using DT.DAL;
using DT.DTO;
using MS.BLL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DT.WEB.Controllers
{
    public class ClassManagementController : BaseController
    {
        // GET: ClassManagement
        public ActionResult Index()
        {
            ViewBag.Title = LOCAL.Objects.Tables.Classes;
            ViewBag.SubDirectory = LOCAL.Components.WebMenuItems.My_Classes;
            List<_Class> classes = new List<_Class>();
            if (CurrentUser.role_id == 1 || CurrentUser.role_id == 2)
            {
                using (Repository<DT.DTO._Class> Repository = new Repository<DT.DTO._Class>())
                {
                    Repository.Include(nameof(_Class.ClassStudents), nameof(_Class.Clusters));
                    classes = Repository.MultiSelectByQuery(x => x.is_active).ToList();
                }
                using (Ctx ctx = new Ctx())
                {
                    classes.ForEach(_class => _class.ClassStudents.ToList().ForEach(x => x.User = ctx.Users.Find(x.student_id)));
                    classes.ForEach(_class => _class.Clusters.ToList().ForEach(x => x.ClusterStudents = ctx.ClusterStudents.Where(s => s.cluster_id == x.id).ToList()));
                }
                return View(classes);
            }
            else if (CurrentUser.role_id == 3)
            {
                using (Repository<DT.DTO._Class> Repository = new Repository<DT.DTO._Class>())
                {
                    Repository.Include(nameof(_Class.ClassStudents), nameof(_Class.Clusters));
                    classes = Repository.MultiSelectByQuery(t =>
                    t.is_active && t.created_by == CurrentUser.id).ToList();
                }
                using (Ctx ctx = new Ctx())
                {
                    classes.ForEach(_class => _class.ClassStudents.ToList().ForEach(x => x.User = ctx.Users.Find(x.student_id)));
                    classes.ForEach(_class => _class.Clusters.ToList().ForEach(x => x.ClusterStudents = ctx.ClusterStudents.Where(s => s.cluster_id == x.id).ToList()));
                }
                return View(classes);
            }
            else
                return RedirectToAction("Index", "Home");
        }

        public ActionResult AddUpdate(int id = 0, bool just_student = false)
        {
            ViewBag.Title = (id==0?"Add ":"Update ") + LOCAL.Objects.Entity._Class;
            DT.DTO._Class _class = new DT.DTO._Class();
            _class.teacher_id = CurrentUser.id;
            ViewBag.JustStudent = just_student;
            if (id != 0)
            {
                using (Repository<DT.DTO._Class> Repository = new Repository<DT.DTO._Class>())
                {
                    Repository.Include(nameof(_Class.ClassStudents));
                    _class = Repository.SingleSelectByQuery(x => x.id == id);
                }
                _class.ClassStudents.ToList().ForEach(x => x.User = StaticDB.Users.GetById(x.student_id));
            }
            _class.students = _class.ClassStudents.Select(c => c.student_id).ToArray();
            return PartialView("_AddUpdatePartialModal", _class);
        }

        [ValidateInput(false)]
        [HttpPost]
        public ActionResult AddUpdate(DT.DTO._Class _class)
        {
            ViewBag.Title = (_class.id == 0 ? "Add " : "Update ") + LOCAL.Objects.Entity._Class;
            try
            {
                _class.max_student_limit = _class.students.Length;
                using (Repository<DT.DTO._Class> Repository = new Repository<DT.DTO._Class>())
                {
                    if (_class.id == 0)
                        _class = Repository.Inserted(_class);
                    else
                    {
                        _class = Repository.Updated(_class);
                    }

                }
                using (Repository<DT.DTO._Class> Repository = new Repository<DT.DTO._Class>())
                {
                    Repository.ExecuteSQL($"DELETE FROM ClassStudents WHERE class_id={_class.id}");

                }
                foreach (int student_id in _class.students)
                {
                    using (Repository<ClassStudent> Repository = new Repository<ClassStudent>())
                    {
                        ClassStudent entity = new ClassStudent();
                        entity.class_id = _class.id;
                        entity.student_id = student_id;
                        Repository.Inserting(entity);
                    }
                }
                return Json(new { Result = true });
            }
            catch (Exception ex)
            {
                return Json(new { Result = false, Message = ex });
            }
        }

        public ActionResult Clustering(int id)
        {
            _Class @class = new _Class();
            using (Repository<_Class> Repository = new Repository<_Class>())
            {
                Repository.Include(nameof(_Class.Clusters));
                StaticDB.Classes = Repository.MultiSelectByQuery(c => c.is_active).ToList();
                @class = StaticDB.Classes.GetById(id);
            }
            return PartialView("_AddUpdateClusterPartialModal", @class);
        }
        [HttpPost]
        public ActionResult ClusterSelectedStudents(int id, ClassStudent[] students)
        {
            Cluster cluster = new Cluster();
            using (Repository<Cluster> Repository = new Repository<Cluster>())
            {
                cluster.class_id = id;
                cluster.title = $"{LOCAL.Objects.Entity.Cluster}-{StaticDB.Clusters.Count(c=>c.class_id == id) + 1}";
                System.Drawing.Color color = Utilities.getRandomColor();
                cluster.color_code = "#" + color.R.ToString("X2") + color.G.ToString("X2") + color.B.ToString("X2");
                cluster = Repository.Inserted(cluster);
            }
            foreach (ClassStudent student in students)
            {
                using (Repository<ClusterStudent> Repository = new Repository<ClusterStudent>())
                {
                    ClusterStudent clusterStudent = new ClusterStudent();
                    clusterStudent.cluster_id = cluster.id;
                    clusterStudent.class_student_id = student.student_id;
                    Repository.Inserting(clusterStudent);
                }
            }
            _Class @class = new _Class();
            using (Repository<_Class> Repository = new Repository<_Class>())
            {
                Repository.Include(nameof(_Class.Clusters));
                Repository.Include(nameof(_Class.ClassStudents));
                @class = Repository.SingleSelectByQuery(c => c.id == id);
            }
            @class.ClassStudents.ToList().ForEach(c => c.User = StaticDB.Users.GetById(c.student_id));
            @class.Clusters = StaticDB.Clusters.Where(c => c.class_id == id).ToList();
            @class.Clusters.ToList().ForEach(x => x.ClusterStudents = StaticDB.ClusterStudents.Where(s => s.cluster_id == x.id).ToList());
            return PartialView("_ClassBodyPartial", @class);
        }
        [HttpPost]
        public ActionResult DeleteSelectedStudents(int id, ClassStudent[] students)
        {
            string clusterStudentDeleteQuery = "", classStudentDeleteQuery = "";
            foreach (ClassStudent classStudent in students)
            {
                clusterStudentDeleteQuery += $"DELETE CS FROM ClusterStudents CS " +
                    $"LEFT JOIN Clusters C on C.id = CS.cluster_id " +
                    $"WHERE CS.class_student_id = {classStudent.student_id} AND C.class_id = {id};{Environment.NewLine}";
                classStudentDeleteQuery += $"DELETE FROM ClassStudents WHERE id={classStudent.student_id};{Environment.NewLine}";
            }
            using (Repository<Cluster> Repository = new Repository<Cluster>())
            {
                Repository.ExecuteSQL(clusterStudentDeleteQuery);
                Repository.ExecuteSQL(classStudentDeleteQuery);
            }
            StaticDB.SetProperty(nameof(Cluster));
            StaticDB.SetProperty(nameof(ClusterStudent));
            StaticDB.SetProperty(nameof(ClassStudent));
            _Class @class = new _Class();
            using (Repository<_Class> Repository = new Repository<_Class>())
            {
                Repository.Include(nameof(_Class.Clusters));
                Repository.Include(nameof(_Class.ClassStudents));
                @class = Repository.SingleSelectByQuery(c => c.id == id);
            }
            @class.ClassStudents.ToList().ForEach(c => c.User = StaticDB.Users.GetById(c.student_id));
            @class.Clusters = StaticDB.Clusters.Where(c => c.class_id == id).ToList();
            @class.Clusters.ToList().ForEach(x => x.ClusterStudents = StaticDB.ClusterStudents.Where(s => s.cluster_id == x.id).ToList());
            return PartialView("_ClassBodyPartial", @class);
        }
        [HttpPost]
        public ActionResult GetClusterStudents(int id)
        {
            List<ClusterStudent> students = new List<ClusterStudent>();
            using (Repository<ClusterStudent> Repository = new Repository<ClusterStudent>())
            {
                Repository.Include(nameof(ClusterStudent.ClassStudent));
                students = Repository.MultiSelectByQuery(c => c.cluster_id == id).ToList();
            }
            students.ForEach(s => s.ClassStudent.User = StaticDB.Users.GetById(s.ClassStudent.student_id));
            return PartialView("_ClusterStudentsPartial", students);
        }
        [HttpPost]
        public ActionResult Clustering(int id, string type, int value)
        {
            _Class currentClass = StaticDB.Classes.GetById(id);
            currentClass.ClassStudents = StaticDB.ClassStudents.Where(c => c.class_id == id).ToList();

DT.WEB/Views/ClassManagement/Create.cshtml
@model _Class
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section styles{
    <style>
        .bg {
            background: -webkit-linear-gradient(left, #50764f, #53c64f);
            margin-top: 3%;
            padding: 3%;
            border-radius: 2.5rem;
            text-align:center;
        }
        label{
            color:white;
        }
        select {
            width: 50%;
            border-radius: 1rem;
            padding: 1.5%;
            color: #fff;
            background-color: #0062cc;
            border: none;
            cursor: pointer;
            margin-right: 6%;
            margin-left:30px;
            background-color: white;
            color: #405b3e;
            margin-top: 4%;
        }

        option {
            background-color: white;
            color: #405b3e;
        }

        .classButton {
            width: 30%;
            border-radius: 1rem;
            padding: 1.5%;
            color: #fff;
            background-color: #0062cc;
            border: none;
            cursor: pointer;
            margin-right: 6%;
            background-color: #405b3e;
            color: white;
            margin-top: 4%;
        }

    </style>


}
<div class="container bg">
    <div class="row">
        <div class="col-md-12">
            @using (Html.BeginForm())
            {
                <div class="form-group">
                    <label>Task Type</label>
                    <select id="task-type">
                        <option>Please Choose</option>
                        <option value="single">Single</option>
                        <option value="multiple">Multiple</option>
                    </select>
                </div>
                <div class="form-group">
                    <label>Task List Type</label>
                    <select id="task-list-type">
                        <option>Please Choose</option>
                        <option value="my">My Tasks</option>
                        <option value="all">All Tasks</option>
                    </select>
                </div>
                <div class="form-group">
                    <label>Task List</label>
                    <select id="task-list">
                        <option>Please Choose</option>
                    </select>
                </div>
            }
        </div>
    </div>

    <input type="button" name="publishButton" class="classButton" value="Publish Now" id="btnPublish"/>
    <input type="button" name="schedulePublishButton" 
           class="classButton" 
           value="Schedule Publishing" 
           id="btnSchedule" 
           data-url="@Url.Action("Schedule")" 
           data-modal="#partial-modal"
           onclick="PartialShow(this);"/>
</div>
    @section scripts{
        <script>
        var allTasks = @Html.Raw(ViewBag.AllTasks.ToJson());
        var myTasks = @Html.Raw(ViewBag.MyTasks.ToJson());
        $(function () {
            $('#task-type').change(function () {
                if ($('#task-list').val())
                    if (!confirm('Would you like to change Task Type? All selected tasks will be cleared.'))
                        return;
                $('#task-list').val('');
                if ($(this).val() == 'single')
                    $('#task-list').removeAttr('multiple');
                else
                    $('#task-list').attr('multiple', 'multiple');
            });
            $('#task-list-type').change(function () {
                if ($(this).val() == 'my') {
                    GetTasks(@Request.User().id);
                    //LoadTasks(myTasks);
                } else {
                    GetTasks(0);
                    //LoadTasks(allTasks);
                }
            });
        });

        function LoadTasks(tasks) {
            $('#task-list').html('');
            $('#task-list').append('<option>Please Choose</option>')
            for (var i = 0; i < tasks.length; i++) {
                var id = tasks[i].id;
                var title = tasks[i].title;
                $('#task-list').append('<option value="' + id + '">' + title + '</option>')
            }
        }
        function GetTasks(created_by) {
            jQuery.ajax({
                url: '@Url.Action("GetTasksList","ClassManagement")',
                dataType: 'json',
                beforeSend: function () {

                },
                complete: function () {

                },
                data: {
                    created_by :created_by
                },
                success: function (data) {
                    LoadTasks(data.list);
                },
                error: function (ex) {

                }
            });
        }
        </script>
    }

DT.WEB/Views/ClassManagement/_AddUpdateClusterPartialModal.cshtml
@model _Class
<div class="modal-dialog" id="cluster-edit-dialog">
    <div class="modal-content">
        <!-- Modal Header -->
        <div class="modal-header">
            <h4 class="modal-title">
                Clustering Options
            </h4>
            <button type="button" class="close" onclick="CloseModal(this)" data-target="#cluster-edit-dialog"><i class="fas fa-times"></i></button>
        </div>
        <!-- Modal body -->
        <div class="modal-body">
            <div class="form-group">
                <label>Number of Clusters</label>
                <input class="form-control" type="number" step="1" min="1" id="clusters-count" onfocus="$('#cluster-size').val('')" value="@Model.Clusters.Count()" autofocus />
            </div>
        </div>
        <div class="modal-body text-center">
            <strong class="text-center w-100">
                OR
            </strong>
        </div>
        <div class="modal-body">
            <div class="form-group">
                <label>Number of Students per cluster</label>
                <input class="form-control" type="number" step="1" min="1" id="cluster-size" onfocus="$('#clusters-count').val('')" />
            </div>
        </div>
        <!-- Modal footer -->
        <div class="modal-footer">
            <button type="button" class="btn btn-primary" onclick="CloseModal(this)" data-target="#cluster-edit-dialog">@DT.LOCAL.Components.Buttons.Cancel</button>
            <button type="button" id="btn-save-cluster" class="btn btn-success" onclick="Create();">@DT.LOCAL.Components.Buttons.Create</button>
        </div>
    </div>
</div>
<script>
    function Create() {
        if (isPartialContinue) {
            ShowAlert('@DT.LOCAL.Messages.Warnings.DialogTitle', '@DT.LOCAL.Messages.Warnings.PreviousProgressHasBeenContinued', '@DT.LOCAL.Components.Buttons.Ok');
            return;
        }
        var model = {
            id : @Model.id,
            type: "",
            value: 0
        }
        var clustersCount = $('#clusters-count').val();
        var clusterSize = $('#cluster-size').val();
        if (!clustersCount && !clusterSize)
            return;
        if (clustersCount =='' && clusterSize == '')
            return;
        if (clustersCount) {
            model.type = 'byCount';
            model.value = parseInt(clustersCount);
        } else {
            model.type = 'bySize';
            model.value = parseInt(clusterSize);
        }
        var body = $('.class-body[data-id="@Model.id"]');
         $.ajax({
            type: "POST",
            cache: false,
            contentType: "application/json; charset=utf-8",
            url: '@Url.Action("Clustering", "ClassManagement")',
            data: JSON.stringify(model),
            beforeSend: function () {
                isPartialContinue = true;
                $(body).append('<div class="overlay"><i class="fas fa-3x fa-sync-alt fa-spin"></i></div>');
            },
            complete: function () {
                $(body).remove('.overlay');
                isPartialContinue = false;
            },
            success: function (data) {
                $(body).html(data);
                $(PartialModal).modal('toggle');
            }
         });
    }
</script>

DT.WEB/Views/ClassManagement/_AddUpdatePartialModal.cshtml
@model _Class
<div class="modal-dialog" id="class-edit-dialog">
    <div class="modal-content">
        <!-- Modal Header -->
        <div class="modal-header">
            @if (!ViewBag.JustStudent)
            {
                <h4 class="modal-title">@(Model.id == 0? DT.LOCAL.Components.Labels.CreateClass: DT.LOCAL.Components.Labels.EditClass)</h4>
            }
            else
            {
                <h4 class="modal-title">
                    Add Student
                </h4>
            }

            <button type="button" class="close" onclick="CloseModal(this)" data-target="#class-edit-dialog"><i class="fas fa-times"></i></button>
        </div>
        <!-- Modal body -->
        <div class="modal-body">

            <div class="form-group">
                <label for="title">@DT.LOCAL.Components.Labels.Title</label>
                @Html.TextBoxFor(m => m.title, new { @class = "form-control", id = "class-title" })
            </div>
            <div class="form-group">
                <label>@DT.LOCAL.Objects.Columns.details</label>
                @Html.TextAreaFor(m => m.details, new { @class = "form-control", id = "class-details", rows = "3" })
            </div>
            @*<div class="form-group">
                <label for="maxStudentLimit">@DT.LOCAL.Components.Labels.MaxStudentLimit</label>
                @Html.TextBoxFor(m => m.max_student_limit, "{0:N0}", new { @class = "form-control", type = "number", id = "class-max_student_limit" })
            </div>*@
            <div class="form-group">
                <label>@DT.LOCAL.Objects.Tables.ClassStudents</label>
                @Html.ListBoxFor(M => M.students, new MultiSelectList(Model.ClassStudents, "student_id", "Student"), new { @class = "form-control", multiple = "multiple", id = "class-student", style = "width: 100%" })
            </div>
            <!-- Modal footer -->
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" onclick="CloseModal(this)" data-target="#class-edit-dialog">@DT.LOCAL.Components.Buttons.Cancel</button>
                <button type="button" id="btn-save-class" class="btn btn-success" onclick="Save();">@DT.LOCAL.Components.Buttons.Save</button>
            </div>
        </div>
    </div>
</div>
<script>
    var entity = @Html.Raw(Model.ToJson());
    if (entity.id != 0) {
        $('#class-student').val(entity.students);
        $('#class-student').trigger('change');
    }
    $(function () {
        jQuery('#class-student').select2({
            allowClear: true,
            placeholder: PleaseChoose[Credentials.Language.iso_code],
            language: Credentials.Language.iso_code,
            ajax: {
                url: '@Url.Action("GetStudents","StudentManagement")',
                data: function (params) {
                    var query = {
                        search: params.term
                    }

                    // Query parameters will be ?search=[term]&type=public
                    return query;
                },
                dataType: 'json'
            }
        }).on('select2:select', function (e) {

            @*var maxLimit = parseInt($('#class-max_student_limit').val());

            if (!maxLimit)
                maxLimit = parseInt(entity.max_student_limit);
            console.log('Max Limit : ' + maxLimit);
            var stuCount = $('#class-student').val().length;
            console.log('Student Count : ' + stuCount);

            if (stuCount > maxLimit)
                ShowInfo('@DT.LOCAL.Messages.Warnings.SelectedStudentsCountOnLimit', '@DT.LOCAL.Messages.Warnings.DialogTitle');*@
        }).trigger('change');
    });

    function Save() {

        entity.title = $('#class-title').val();
        entity.details = $('#class-details').val();
        entity.teacher_id = @Model.teacher_id;
        entity.students = $('#class-student').val();
        console.info(entity);
        if (!entity.title) {
            ShowAlert('@DT.LOCAL.Messages.Warnings.DialogTitle', '@string.Format(DT.LOCAL.Messages.Warnings.FieldRequired, DT.LOCAL.Objects.Columns.title)', '@DT.LOCAL.Components.Buttons.Ok');
        }
        else {
            if (isPartialContinue) {
                alert("Previous request is being continued. Please wait...");
                return;
            }
            var btnContent = $('#btn-save-class').html();
            $.ajax({
                type: "POST",
                url: '@Url.Action("AddUpdate", "ClassManagement")',
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                data: JSON.stringify(entity),
                success: function (data) {
                    if (data['Result']) {
                        location.reload();
                    } else {
                        ShowAlert('@DT.LOCAL.Messages.Warnings.DialogTitle', data.Message, '@DT.LOCAL.Components.Buttons.Ok');
                    }
                },
                beforeSend: function () {
                    isPartialContinue = true;
                    $('body').append('<div class="overlay"><i class="fas fa-3x fa-sync-alt fa-spin"></i></div>');
                    $('#btn-save-class').html('<i class="fas fa-sync-alt fa-spin"></i>');
                },
                complete: function () {
                    isPartialContinue = false;
                    $('body.overlay').fadeOut(250, function () {
                        $(this).remove();
                    });
                    $('#btn-save-class').html(btnContent);
                },
                error: function (XMLHttpRequest, textStatus, errorThrown) {
                    ShowAlert('@DT.LOCAL.Messages.Warnings.DialogTitle', errorThrown, '@DT.LOCAL.Components.Buttons.Ok');
                }
            });
        }
    }
</script>

DT.WEB/Views/ClassManagement/_ClassBodyPartial.cshtml
@model _Class
@{
    List<int> classStudentIds = new List<int>();
}
<div class="row">
    @foreach (Cluster cluster in Model.Clusters)
    {
        classStudentIds.AddRange(cluster.ClusterStudents.Select(x => x.class_student_id));
        <div class="col-6 animate__animated animate__bounceIn">
            <div class="info-box cursor-pointer" data-id="@cluster.id" data-range="@cluster.ClusterStudents.Count" data-class-id="@Model.id" onclick="ShowMenu(this)">
                <span class="info-box-icon" style="background-color:@cluster.color_code">
                    <i class="fab fa-buromobelexperte"></i>
                </span>

                <div class="info-box-content">
                    <span class="info-box-text">@cluster.title</span>
                    <span class="info-box-number">@cluster.ClusterStudents.Count</span>
                </div>
                <!-- /.info-box-content -->
            </div>
            <!-- /.info-box -->
        </div>
    }
</div>
@{
    var nonClusteredStudents = Model.ClassStudents.Where(x => !classStudentIds.Contains(x.id));
}
@if (nonClusteredStudents.Count() > 0)
{
    <table class="index-table cell-border display table-bordered table-responsive" style="width:100% !important;">
        <thead>

            <tr>
                <th>@DT.LOCAL.Components.Labels.NonClusteredStudents</th>
            </tr>
        </thead>
        <tbody>

            @foreach (ClassStudent classStudent in Model.ClassStudents.Where(x => !classStudentIds.Contains(x.id)))
            {

                <tr>
                    <td>
                        <div class="icheck-primary">
                            <input class="form-control student-check" type="checkbox" id="chk-@Model.id-@classStudent.id" data-class-id="@Model.id" data-id="@classStudent.id" />
                            <label for="chk-@Model.id-@classStudent.id" style="font-weight:400;">
                                @classStudent.Student
                            </label>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

DT.WEB/Views/ClassManagement/_ClusterStudentsPartial.cshtml
@model List<ClusterStudent>

@{
    User current_user = Request.User();
}
<link href="~/Content/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
<table class="clusterStudents-table cell-border display table-bordered table-responsive responsive" style="width:100% !important;">
    <thead>
        <tr>
            <th>@DT.LOCAL.Objects.Columns.name</th>
            <th>@DT.LOCAL.Objects.Columns.lastname</th>
            <th>@DT.LOCAL.Objects.Columns.mail</th>
            <th>@DT.LOCAL.Objects.Columns.ui_language</th>
            <th></th>
        </tr>
    </thead>
    <tbody>

        @foreach (ClusterStudent clusterStudent in Model)
        {
            <tr data-id="@clusterStudent.id">

                <td>@clusterStudent.ClassStudent.User.name.ToStr()</td>
                <td>@clusterStudent.ClassStudent.User.lastname.ToStr()</td>
                <td>@clusterStudent.ClassStudent.User.mail.ToStr()</td>
                <td>@StaticDB.Languages.GetByIso(clusterStudent.ClassStudent.User.ui_language)</td>
                <td>

                    <button type="button" class="btn btn-tool" data-id="@clusterStudent.id" onclick="Remove(this);">
                        <i class="fas fa-trash"></i>
                    </button>
                </td>
            </tr>
        }
    </tbody>
</table>


<script src="~/Content/plugins/datatables/jquery.dataTables.min.js"></script>
<script>
    var datatable = $('.clusterStudents-table').DataTable({
        'autoWidth': false,
        'ordering': true,
        'order': [[0, 'asc']],
        'paging': false,
        'searching': false,
        'info': false,
        'responsive': true,
        'language': {
            'url': Credentials.Server + 'Content/plugins/datatables/en.json'
        }
    });
    async function Remove(elm) {
        var id = $(elm).data('id');
        await AddRemove(elm);
        $('tr[data-id="' + id + '"]').fadeOut("slow", function () {
            $(this).remove();
            ++removedCount;
        });
        if (removedCount <= parseInt('@ViewBag.SelectedTasksCount'))
            $(PartialModal).modal('toggle');
    }
</script>