DT.WEB/Controllers/TaskAssignmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DT.DAL;
using DT.DTO;
using DT.WEB.Models;
using MS.BLL;

namespace DT.WEB.Controllers
{
    public class TaskAssignmentController : BaseController
    {
        public ActionResult AssignTaskModal(int id, int assign_id, string assign_table)
        {
            SessionTask sessionTask = new SessionTask();
            sessionTask.task_id = id;
            sessionTask.planned_start_time = Zaman.Simdi;
            sessionTask.assigned_table = assign_table;
            if (assign_table.Equals("Class"))
                sessionTask.class_id = assign_id;
            else if (assign_table.Equals(nameof(Cluster)))
                sessionTask.cluster_id = assign_id;
            else if (assign_table.Equals(nameof(Room)))
                sessionTask.room_id = assign_id;
            return PartialView("_AssignTaskModal", sessionTask);
        }
        public ActionResult AssignSequenceModal(int id, int assign_id, string assign_table)
        {
            List<SessionTask> sessionTasks = new List<SessionTask>();
            int index = 1;
            foreach (SequenceTask  sequenceTask in StaticDB.SequenceTasks.Where(x=>x.is_active && x.sequence_id == id).OrderBy(s=>s.index_order))
            {
                SessionTask sessionTask = new SessionTask();
                sessionTask.task_id = sequenceTask.task_id;
                sessionTask.assigned_table = assign_table;
                if (assign_table.Equals("Class"))
                    sessionTask.class_id = assign_id;
                else if (assign_table.Equals(nameof(Cluster)))
                    sessionTask.cluster_id = assign_id;
                else if (assign_table.Equals(nameof(Room)))
                    sessionTask.room_id = assign_id;
                sessionTask.id = index++;
                sessionTask.sequence_id = id;
                sessionTask.Task = StaticDB.Tasks.GetById(sessionTask.task_id);
                sessionTasks.Add(sessionTask);
            }
            return PartialView("_AssignSequenceModal", sessionTasks);
            //ViewBag.sequence_id = id;
            //ViewBag.assigned_table = assign_table;
            //ViewBag.assign_id = assign_id;
            //List<SequenceTask> sequenceTasks = StaticDB.SequenceTasks.Where(x => x.is_active && x.sequence_id == id).OrderBy(s => s.index_order).ToList();
            //sequenceTasks.ForEach(x => x.Task = StaticDB.Tasks.GetById(x.task_id));
            //return PartialView("_AssignSequenceModal", sequenceTasks);
        }
        [HttpPost]
        public ActionResult AssignTask(SessionTask sessionTask, bool send_mail)
        {
            try
            {
                List<SessionTask> sessionTasks = Clusterization(sessionTask);
                List<SessionTask> assignedSessionTasks = new List<SessionTask>();
                foreach (SessionTask st in sessionTasks)
                {
                    SessionTask createdST = SaveAndSendSessionTask(st);
                    if (send_mail)
                    {
                        List<User> users = createdST.SessionTaskParticipants.Select(x => x.User).ToList();
                        for (int i = 0; i < users.Count; i++)
                        {
                            User user = users[i];
                            DTHelper.SendTaskAssignmentMail(user, createdST);
                        }
                    }
                    assignedSessionTasks.Add(createdST);
                }
                return Json(new { Result = true }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { Result = false, Message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        private static List<SessionTask> Clusterization(SessionTask sessionTask)
        {
            List<SessionTask> sessionTasks = new List<SessionTask>();
            if (sessionTask.assigned_table.Equals("Class"))
            {
                List<Cluster> clusters = StaticDB.Clusters.Where(c => c.is_active && c.class_id == sessionTask.class_id).ToList();
                if (clusters == null || clusters.Count == 0)
                    sessionTasks.Add(sessionTask);
                else
                {
                    SessionTask st = sessionTask.Clone();
                    foreach (Cluster cluster in clusters)
                    {
                        st.assigned_table = nameof(Cluster);
                        st.class_id = null;
                        st.cluster_id = cluster.id;
                        sessionTasks.Add(st);
                    }
                }
            }
            return sessionTasks;
        }

        [HttpPost]
        public ActionResult AssignSequence(List<SessionTask> sessionTasks, bool send_mail)
        {
            try
            {
                List<SessionTask> clusterizedSessionTasks = new List<SessionTask>();
                List<SessionTask> savedSessionTasks = new List<SessionTask>();
                foreach (SessionTask sessionTask in sessionTasks)
                {
                    clusterizedSessionTasks.AddRange(Clusterization(sessionTask));
                }
                foreach (SessionTask sessionTask in clusterizedSessionTasks)
                {
                    SessionTask task = SaveAndSendSessionTask(sessionTask);
                    task.id = 0;
                    savedSessionTasks.Add(task);
                }
                if (send_mail && savedSessionTasks.Count > 0)
                {
                    List<User> users = savedSessionTasks[0].SessionTaskParticipants.Select(x => x.User).ToList();
                    for (int i = 0; i < users.Count; i++)
                    {
                        User user = users[i];
                        DTHelper.SendSequenceAssignmentMail(user, savedSessionTasks);
                    }
                }
                return Json(new { Result = true }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { Result = false, Message=ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }
        private static SessionTask SaveAndSendSessionTask(SessionTask sessionTask)
        {
            using (Repository<SessionTask> Repository = new Repository<SessionTask>())
            {
                sessionTask = Repository.Inserted(sessionTask);
            }
            List<User> participants = new List<User>();
            using (Ctx ctx = new Ctx())
            {
                if (sessionTask.assigned_table.Equals("Class"))
                    participants = ctx.Database.SqlQuery<User>(string.Format(LOCAL.Objects.DBScripts.GetUsersByClassId, sessionTask.class_id)).ToList();
                else if (sessionTask.assigned_table.Equals(nameof(Cluster)))
                    participants = ctx.Database.SqlQuery<User>(string.Format(LOCAL.Objects.DBScripts.GetUsersByClusterId, sessionTask.cluster_id)).ToList();
                else if (sessionTask.assigned_table.Equals(nameof(Room)))
                    participants = ctx.Database.SqlQuery<User>(string.Format(LOCAL.Objects.DBScripts.GetUsersByRoomId, sessionTask.room_id)).ToList();
            }
            foreach (User user in participants)
            {
                SessionTaskParticipant sessionTaskParticipant = new SessionTaskParticipant();
                using (Repository<SessionTaskParticipant> Repository = new Repository<SessionTaskParticipant>())
                {
                    sessionTaskParticipant.session_task_id = sessionTask.id;
                    sessionTaskParticipant.participant_id = user.id;
                    sessionTaskParticipant = Repository.Inserted(sessionTaskParticipant);
                }
                sessionTaskParticipant.User = user;
                sessionTaskParticipant.SessionTask = sessionTask;
                sessionTask.SessionTaskParticipants.Add(sessionTaskParticipant);
            }

            DTHelper.SetTaskUsage(sessionTask.task_id);
            return sessionTask;
        }
        public ActionResult AssignTaskToClass(int id)
        {
            _Class _class = null;
            using (Repository<_Class> Repository = new Repository<_Class>())
            {
                Repository.Include(nameof(_Class.ClassStudents), nameof(_Class.Clusters));
                _class = Repository.SingleSelectByQuery(x => x.id == id && x.is_active);
            }
            Cacher.Save("Class", _class);
            Cacher.Save("SelectedTasks", new List<SequenceTask>());
            Request.Cookies.Remove("TaskAddStatus");
            return View("ClassTaskAssignment");
        }
        public ActionResult AssignSequenceToClass(int id)
        {
            _Class _class = null;
            using (Repository<_Class> Repository = new Repository<_Class>())
            {
                Repository.Include(nameof(_Class.ClassStudents), nameof(_Class.Clusters));
                _class = Repository.SingleSelectByQuery(x => x.id == id && x.is_active);
            }
            Cacher.Save("Class", _class);
            Cacher.Save("SelectedTasks", new List<SequenceTask>());
            Request.Cookies.Remove("TaskAddStatus");
            return View("ClassTaskAssignment");
        }
        public ActionResult GetTasks(string type = "My")
        {
            ViewData["Type"] = type;
            try
            {
                List<_Task> tasks = new List<_Task>();
                using (Repository<_Task> Repository = new Repository<_Task>())
                {
                    var ts = Repository.MultiSelectByQuery(t => t.is_active && t.status.Equals(nameof(LOCAL.Enums.StatusTypes.Published)));
                    tasks = type == "My" ?
                        ts.Where(t => t.created_by == CurrentUser.id).ToList() :
                        ts.ToList();

DT.WEB/Views/TaskAssignment/ClassTaskAssignment.cshtml
@{
    ViewBag.Title = "AddUpdate";
    Layout = "~/Views/Shared/_Layout.cshtml";
    User current_user = Request.User();
}

@section styles{
    <!-- Range Slider -->
    <link href="~/Content/plugins/ion-rangeslider/css/ion.rangeSlider.min.css" rel="stylesheet" />
    <!-- Bootstrap Toggle -->
    <link href="~/Content/plugins/bootstrap-toggle/css/bootstrap4-toggle.min.css" rel="stylesheet" />
    <style>
        .task-type {
            transition: ease-in-out 0.3s all;
        }

            .task-type:hover {
                box-shadow: 0 0 20px #000;
            }
    </style>
}

<div class="card card-primary card-outline">
    <div class="card-header">
        <h3 class="card-title">
            <i class="fas fa-edit"></i>
            TASK ASSIGNMENT
        </h3>

        <div class="card-tools" id="selected-tasks">

        </div>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-5 col-sm-3">
                <div class="nav flex-column nav-tabs h-100" id="vert-tabs-tab" role="tablist" aria-orientation="vertical">
                    <a class="nav-link active" id="task-selection-tab" data-toggle="pill" href="#task-selection" role="tab" aria-controls="task-selection" aria-selected="true">
                        Task Type Selection
                    </a>
                    <a class="nav-link" id="tasks-list-tab" data-toggle="pill" href="#tasks-list" role="tab" aria-controls="tasks-list" aria-selected="false">
                        Task List
                    </a>
                    <a class="nav-link" id="vert-tabs-messages-tab" data-toggle="pill" href="#vert-tabs-messages" role="tab" aria-controls="vert-tabs-messages" aria-selected="false">

                    </a>
                    <a class="nav-link" id="vert-tabs-settings-tab" data-toggle="pill" href="#vert-tabs-settings" role="tab" aria-controls="vert-tabs-settings" aria-selected="false">

                    </a>
                </div>
            </div>
            <div class="col-7 col-sm-9">
                <div class="tab-content" id="vert-tabs-tabContent">
                    <div class="tab-pane text-left fade show active" id="task-selection" role="tabpanel" aria-labelledby="task-selection-tab">
                        <div class="row">
                            <div class="col-6">
                                <a href="#" onclick="$('#tasks-list-tab').tab('show');">
                                    <div class="card task-type">
                                        <div class="card-header">
                                            <h3 class="card-title">
                                                Single Task
                                            </h3>
                                        </div>
                                        <div class="card-body">
                                            <img class="card-img" src="~/Content/img/task-types/single-task.png" />
                                        </div>
                                        <div class="card-footer">
                                            Single task explanation
                                        </div>
                                    </div>
                                </a>
                            </div>
                            <div class="col-6">
                                <a href="#" onclick="$('#tasks-list-tab').tab('show');">
                                    <div class="card task-type">
                                        <div class="card-header">
                                            <h3 class="card-title">
                                                Sequence
                                            </h3>
                                        </div>
                                        <div class="card-body">
                                            <img class="card-img" src="~/Content/img/task-types/multiple-task.png" />
                                        </div>
                                        <div class="card-footer">
                                            Sequence explanation
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="tasks-list" role="tabpanel" aria-labelledby="tasks-list-tab">
                        <div class="card card-primary card-outline card-outline-tabs">
                            <div class="card-header p-0 border-bottom-0">
                                <ul class="nav nav-tabs" id="custom-tabs-three-tab" role="tablist">
                                    <li class="nav-item">
                                        <a class="nav-link active" id="my-tasks-tab" data-toggle="pill" href="#my-tasks" role="tab" aria-controls="my-tasks" aria-selected="true" onclick="GetTasksByType('My');">
                                            My Tasks
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" id="all-tasks-tab" data-toggle="pill" href="#all-tasks" role="tab" aria-controls="all-tasks" aria-selected="false" onclick="GetTasksByType('All');">
                                            All Tasks
                                        </a>
                                    </li>
                                </ul>
                            </div>
                            <div class="card-body">
                                <div class="tab-content" id="custom-tabs-three-tabContent">
                                    <div class="tab-pane fade show active" id="my-tasks" role="tabpanel" aria-labelledby="my-tasks-tab">

                                    </div>
                                    <div class="tab-pane fade" id="all-tasks" role="tabpanel" aria-labelledby="all-tasks-tab">

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="vert-tabs-messages" role="tabpanel" aria-labelledby="vert-tabs-messages-tab">

                    </div>
                    <div class="tab-pane fade" id="vert-tabs-settings" role="tabpanel" aria-labelledby="vert-tabs-settings-tab">

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <!-- Range Slider -->
    <script src="~/Content/plugins/ion-rangeslider/js/ion.rangeSlider.min.js"></script>
    <!-- Bootstrap Toggle -->
    <script src="~/Content/plugins/bootstrap-toggle/js/bootstrap4-toggle.min.js"></script>
    <script>
        var lastCall = 'My';
        var isProcessContinue = false;
        $(function () {
            GetTasksByType("My");
            GetSelectedTasks();
        });

        function GetTasksByType(type) {
            if (isProcessContinue) {
                ShowAlert('@DT.LOCAL.Messages.Warnings.DialogTitle', '@DT.LOCAL.Messages.Warnings.PreviousProgressHasBeenContinued', '@DT.LOCAL.Components.Buttons.Ok');
                return;
            }
            lastCall = type;
            var content = $('#my-tasks');
            if (type == 'All')
                content = $('#all-tasks');
            isProcessContinue = true;
            $.ajax({
                url: type == 'My' ? '@Url.Action("GetTasks", "TaskAssignment", new {type="My"})' : '@Url.Action("GetTasks", "TaskAssignment", new { type = "All" })',
                beforeSend: function () {
                    $(content).append('<div class="overlay"><i class="fas fa-3x fa-sync-alt fa-spin"></i></div>');
                },
                success: function (data, textStatus, xhr) {
                    if (textStatus == 'success')
                        $(content).html(data);
                },
                complete: function () {
                    $(content).remove('.overlay');
                    isProcessContinue = false;
                },
                error: function() {
                    ShowAlert('@DT.LOCAL.Messages.Warnings.DialogTitle', '@DT.LOCAL.Messages.Warnings.ServerError', '@DT.LOCAL.Components.Buttons.Ok');
                }
            });
        }
        function GetSelectedTasks() {
            $.ajax({
                url: '@Url.Action("GetSelectedTasksButton", "TaskAssignment")',
                beforeSend: function () {
                    $('#selected-tasks').append('<div class="overlay"><i class="fas fa-3x fa-sync-alt fa-spin"></i></div>');
                },
                success: function (data, textStatus, xhr) {
                    if (textStatus == 'success')
                        $('#selected-tasks').html(data);
                },
                complete: function () {
                    $('#selected-tasks').remove('.overlay');
                    isProcessContinue = false;
                },
                error: function() {
                    ShowAlert('@DT.LOCAL.Messages.Warnings.DialogTitle', '@DT.LOCAL.Messages.Warnings.ServerError', '@DT.LOCAL.Components.Buttons.Ok');
                }
            });

        }
        function AddRemove(elm) {
            var id = $(elm).data('id');
            $.ajax({
                method:'POST',
                url: '@Url.Action("AddRemoveTask", "TaskAssignment")' + '/' + id,
                beforeSend: function () {
                    $('#selected-tasks').append('<div class="overlay"><i class="fas fa-3x fa-sync-alt fa-spin"></i></div>');
                },
                success: function (data, textStatus, xhr) {
                    if (textStatus == 'success') {
                        $('#selected-tasks').html(data);
                        var status = decodeURI($.cookie('TaskAddStatus'));
                        if (status == 'true')
                            $('.btn-add[data-id="'+id+'"]').html('<i class="fas fa-minus"></i>');
                        else
                            $('.btn-add[data-id="' + id + '"]').html('<i class="fas fa-plus"></i>');
                    }
                },
                complete: function () {
                    $('#selected-tasks').remove('.overlay');
                    isProcessContinue = false;
                },
                error: function() {
                    ShowAlert('@DT.LOCAL.Messages.Warnings.DialogTitle', '@DT.LOCAL.Messages.Warnings.ServerError', '@DT.LOCAL.Components.Buttons.Ok');
                }
            });

        }
    </script>
}

DT.WEB/Views/TaskAssignment/_AssignSequenceModal.cshtml
@model List<SessionTask>
@{

}
<link href="~/Content/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
<link href="~/Content/plugins/datatables-responsive/css/responsive.bootstrap4.min.css" rel="stylesheet" />
<div class="modal-dialog modal-xl" id="assign-modal">
    <div class="modal-content">
        <!-- Modal Header -->
        <div class="modal-header">
            <h4 class="modal-title">
                Planning
            </h4>
            <button type="button" class="close" onclick="CloseModal(this)" data-target="#assign-modal"><i class="fas fa-times"></i></button>
        </div>
        <!-- Modal body -->
        <div class="modal-body">
            <table class="cell-border display table-bordered responsive" id="sequence-tasks-table" style="width:100% !important;">
                <thead>
                    <tr>
                        <th>@DT.LOCAL.Objects.Columns.information_gap</th>
                        <th>@DT.LOCAL.Objects.Columns.title</th>
                        <th>@DT.LOCAL.Objects.Columns.target_ages</th>
                        <th>@DT.LOCAL.Objects.Columns.group_range</th>
                        <th>@DT.LOCAL.Objects.Columns.planned_start_date</th>
                        <th>@DT.LOCAL.Objects.Columns.expiration_date</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (SessionTask sessionTask in Model)
                    {
                    <tr>
                        <td>@sessionTask.Task.information_gap</td>
                        <td>@sessionTask.Task.title</td>
                        <td>@sessionTask.Task.target_min_age - @sessionTask.Task.target_max_age</td>
                        <td>@sessionTask.Task.group_range</td>
                        <td>
                            <div class="input-group date" data-type="datetime" id="sd-group-@sessionTask.id" data-target-input="nearest">
                                <input type="text" data-id="@sessionTask.id" class="form-control datetimepicker-input planned_start_time" data-target="#sd-group-@sessionTask.id" value="@Zaman.Simdi" />
                                <div class="input-group-append" data-target="#sd-group-@sessionTask.id" data-toggle="datetimepicker">
                                    <div class="input-group-text">
                                        <i class="fas fa-calendar-alt"></i>
                                    </div>
                                </div>
                            </div>
                        </td>
                        <td>
                            <div class="input-group date" data-type="datetime" id="ed-group-@sessionTask.id" data-target-input="nearest">
                                <input type="text" data-id="@sessionTask.id" class="form-control datetimepicker-input expiration_date" data-target="#ed-group-@sessionTask.id" value="@Zaman.Simdi.AddYears(1)" />
                                <div class="input-group-append" data-target="#ed-group-@sessionTask.id" data-toggle="datetimepicker">
                                    <div class="input-group-text">
                                        <i class="fas fa-calendar-alt"></i>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                    }
                </tbody>
            </table>
        </div>
        <!-- Modal footer -->
        <div class="modal-footer">
            <button type="button" class="btn btn-primary" onclick="CloseModal(this)" data-target="#assign-modal">@DT.LOCAL.Components.Buttons.Cancel</button>
            <button type="submit" id="btn-save-assignment" class="btn btn-success" onclick="SaveSequenceAssignment();">@DT.LOCAL.Components.Buttons.Save</button>
        </div>
    </div>
</div>
 

<script src="~/Content/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="~/Content/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="~/Content/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
<script src="~/Content/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
<script>
    var sessionTasks = @Html.Raw(Model.ToJson());
    $('.index-table').DataTable({
        'autoWidth': false,
        'ordering': false,
        'paging': false,
        'searching': false,
        'info': false,
        'language': {
            'url': Credentials.Server + 'Content/plugins/datatables/en.json'
        }
    });
    function SaveSequenceAssignment() {
        var sts = [];
        for (var i = 0; i < sessionTasks.length; i++) {
            var sessionTask = sessionTasks[i];

            var planned_start_time = $('.planned_start_time[data-id="' + sessionTask.id + '"]').val();
            sessionTask.planned_start_time = planned_start_time;

            var expiration_date = $('.expiration_date[data-id="' + sessionTask.id + '"]').val();
            sessionTask.planned_end_time = expiration_date;
            sts.push(sessionTask);
        }
        $.confirm({
            title: 'Confirm!',
            content: '@DT.LOCAL.Components.Labels.SendMailToParticipant',
            buttons: {
                yes: {
                    text: '@DT.LOCAL.Components.Buttons.Yes',
                    action: function () {
                        SendAssignment(sts, true);
                    }
                },
                no: {
                    text: '@DT.LOCAL.Components.Buttons.No',
                    action: function () {
                        SendAssignment(sts, false);
                    }
                }
            }
        });
    }
    function SendAssignment(sts, mail_status) {
        var model = {
            sessionTasks: sts,
            send_mail: mail_status
        };
        if (isPartialContinue) {
            alert("Previous request is being continued. Please wait...");
            return;
        }
        console.log(JSON.stringify(model));
        var btnContent = $('#btn-save-assignment').html();
        $.ajax({
            type: "POST",
            url: '@Url.Action("AssignSequence", "TaskAssignment")',
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            data: JSON.stringify(model),
            success: function (data) {
                if (data['Result']) {
                    $('#assign-modal').parent('.modal').modal('toggle');
                } else {
                    ShowAlert('@DT.LOCAL.Messages.Warnings.DialogTitle', data.Message, '@DT.LOCAL.Components.Buttons.Ok');
                }
            },
            beforeSend: function () {
                isPartialContinue = true;
                $('#btn-save-assignment').html('<i class="fas fa-sync-alt fa-spin"></i>');
                $('body').append('<div class="overlay"><i class="fas fa-3x fa-sync-alt fa-spin"></i></div>');
            },
            complete: function () {
                isPartialContinue = false;
                $('#btn-save-assignment').html(btnContent);
                $('body.overlay').fadeOut(250, function () {
                    $(this).remove();
                });
            },
            error: function (XMLHttpRequest, textStatus, errorThrown) {
                alert('error');
                ShowAlert('@DT.LOCAL.Messages.Warnings.DialogTitle', errorThrown, '@DT.LOCAL.Components.Buttons.Ok');
            }
        });
    }
</script>

DT.WEB/Views/TaskAssignment/_AssignSequencePartialModal.cshtml
@model Sequence

DT.WEB/Views/TaskAssignment/_AssignableTasksListPartial.cshtml
@model List<_Task>
<div class="row">
    @foreach (_Task task in Model)
    {
        <div class="col-md-6 col-sm-6 col-12 task-box" data-id="@task.id">
            @Html.Partial("_TaskBoxPartial",task, new ViewDataDictionary { {"type", ViewData["Type"] } })
        </div>
    }
</div>

DT.WEB/Views/TaskAssignment/_SelectedTasksButtonPartial.cshtml
<a class="btn btn-tool" href="#" 
   data-url="@Url.Action("GetSelectedTasks","TaskAssignment")"
   data-modal="#partial-modal"
   onclick="PartialShow(this)">
    <i class="fas fa-tasks"></i> Selected Tasks
    @if (ViewBag.SelectedTasksCount > 0)
    {
        <span class="badge badge-warning navbar-badge">@ViewBag.SelectedTasksCount</span>
    }
</a>